### ISSUE TITLE
withReleasy hoists statics

### ISSUE THREAD

**Issue by renatobenks-zz** [releasy/react-releasy#11]
The `withReleasy` HOC is not extending the `static` properties between components from HOC.

https://github.com/releasy/react-releasy/blob/master/src/withReleasy.js#L17

use https://github.com/mridgway/hoist-non-react-statics fix it.

**Comment by sibelius** [comment]
Hoist could be an option

**Comment by renatobenks-zz** [comment]
why an option @sibelius? When I make HOCs, I wanna my static values from the original component to my new component from HOC.

**Comment by sibelius** [comment]
Relay does not do this automatically for perf reason

**Comment by renatobenks-zz** [comment]
It's a point, but there's no another way to share static values without this trade-off?
