### ISSUE TITLE
ReleasyConsumer.render must return a valid react element bug.

### ISSUE THREAD

**Issue by AndreiCalazans** [releasy/react-releasy#7]
![screen shot 2018-02-17 at 09 27 27](https://user-images.githubusercontent.com/20777666/36340491-d973b270-13c4-11e8-9f51-537e8e1806df.png)

**Comment by AndreiCalazans** [comment]
It works with React > v16.0.0
The main issue is that react < 16 doesn't accept array as valid children 
`ReleasyConsumer.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

**Comment by JCMais** [comment]
Do we even need to support React < 16 anyway?

Anyone using Relay with a new project most probably is also using the latest version of React.

**Comment by felippepuhle** [comment]
https://github.com/releasy/react-releasy/blob/master/src/ReleasyConsumer.js#L29

We could turn into a single`React.cloneChild`, forcing users to provide only one child. (I don't see any problems with that since we have `withReleasy`)
